In [1]:
#numpy

In [2]:
#numerical python

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [11]:
#creating arrays 1D

In [12]:
sample_array=np.array([1,2,3,4])

In [13]:
sample_array

array([1, 2, 3, 4])

In [14]:
#2D array(matrix)

In [16]:
sample_array2=np.array([[1,2],[3,4]])

In [17]:
sample_array2

array([[1, 2],
       [3, 4]])

In [18]:
#3D array

In [28]:
sample_array3=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])


In [29]:
sample_array3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
#Dimention
# 0-D (Scalar)-number
# 1-D (vector)-list
# 2-D (matrix)-A table with row and columns
# 3-D (Tensor)-A stack of tables

In [34]:
#Tensor

In [36]:
s_array3=np.array([
    [[91,92],[93,94]],
    [[95,96],[97,98]]
])

In [38]:
s_array3

array([[[91, 92],
        [93, 94]],

       [[95, 96],
        [97, 98]]])

In [39]:
#Array properties

In [42]:
s2_array2=np.array([[1,2,3],[4,5,6]])

In [43]:
s2_array2

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
#shape

In [46]:
s2_array2.shape

(2, 3)

In [50]:
#dimention

In [47]:
s2_array2.ndim

2

In [51]:
#size

In [48]:
s2_array2.size

6

In [49]:
s2_array2.dtype

dtype('int64')

In [52]:
#3d

In [53]:
s_array3=np.array([
    [[91,92],[93,94]],
    [[95,96],[97,98]]
])

In [54]:
s_array3

array([[[91, 92],
        [93, 94]],

       [[95, 96],
        [97, 98]]])

In [57]:
#shape

In [58]:
s_array3.shape

(2, 2, 2)

In [59]:
#dimention

In [60]:
s_array3.ndim

3

In [61]:
#size

In [62]:
s_array3.size

8

In [64]:
#datatype

In [65]:
s_array3.dtype

dtype('int64')

In [66]:
#2D

In [67]:
sample_array2=np.array([[0,0,0],[0,0,0]])

In [68]:
sample_array2

array([[0, 0, 0],
       [0, 0, 0]])

In [70]:
sample_array2=np.array([[1,1,1],[1,1,1]])

In [71]:
sample_array2

array([[1, 1, 1],
       [1, 1, 1]])

In [72]:
#special Arrays

In [73]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [80]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [81]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [83]:
#1D

In [87]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [88]:
a

array([1, 2, 3, 4])

In [89]:
b

array([5, 6, 7, 8])

In [90]:
#add

In [91]:
a+b

array([ 6,  8, 10, 12])

In [94]:
#sub

In [95]:
a-b

array([-4, -4, -4, -4])

In [97]:
#mul

In [98]:
a*b

array([ 5, 12, 21, 32])

In [99]:
#div

In [100]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [101]:
#mathematical functions

In [103]:
sample_array1=np.array([1,4,9])

In [104]:
sample_array1

array([1, 4, 9])

In [105]:
np.sqrt(sample_array1)

array([1., 2., 3.])

In [106]:
#log

In [107]:
np.log(sample_array1)

array([0.        , 1.38629436, 2.19722458])

In [108]:
#expo

In [109]:
np.exp(sample_array1)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [110]:
#stastical function

In [113]:
sample=np.array([1,2,3,4,5,6,7,8,9])

In [114]:
sample

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
#mean

In [118]:
np.mean(sample)

np.float64(5.0)

In [119]:
#median

In [121]:
np.median(sample)

np.float64(5.0)

In [122]:
#standard deviation

In [125]:
np.std(sample)

np.float64(2.581988897471611)

In [126]:
#min

In [130]:
np.min(sample)

np.int64(1)

In [131]:
#max

In [132]:
np.max(sample)

np.int64(9)

In [135]:
arrayx=np.array([68,67,58,1003])

In [136]:
np.mean(array)

np.float64(299.0)

In [137]:
np.median(arrayx)

np.float64(67.5)

In [138]:
np.std(arrayx)

np.float64(406.47324635208156)

In [139]:
np.min(arrayx)

np.int64(58)

In [140]:
np.max(arrayx)

np.int64(1003)

In [141]:
array2=np.array([[1,2],[3,4]])

In [142]:
array2

array([[1, 2],
       [3, 4]])

In [143]:
#convert into 2D to 1D

In [144]:
array2.flatten()

array([1, 2, 3, 4])

In [146]:
s_3=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [147]:
s_3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [148]:
a=np.array([1,2])
b=np.array([3,4])

In [149]:
a

array([1, 2])

In [150]:
b

array([3, 4])

In [151]:
#join

In [157]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [158]:
ar1=np.array([1,2,3,4])

In [159]:
ar1

array([1, 2, 3, 4])

In [167]:
np.array_split(ar1,2)

[array([1, 2]), array([3, 4])]

In [168]:
#random

In [170]:
np.random.rand(10)

array([0.73462053, 0.02295822, 0.95904724, 0.52565222, 0.37639225,
       0.47326307, 0.73319579, 0.8899204 , 0.02202971, 0.12613985])

In [176]:
#int

In [177]:
np.random.randint(0,50,25)

array([29, 48, 31, 28, 42,  3, 44, 33, 42, 20, 45, 21, 44, 14, 16, 38, 42,
       45, 37, 20, 41, 19, 43, 24, 39], dtype=int32)

In [180]:
d2=np.array(([1,2],[3,4]))

In [181]:
d2

array([[1, 2],
       [3, 4]])

In [184]:
np.sum(d2,axis=0)

array([4, 6])

In [185]:
np.sum(d2,axis=1)

array([3, 7])

In [194]:
#missing value ,null,nan

In [195]:
d1=np.array([1,np.nan,3])

In [196]:
d1

array([ 1., nan,  3.])

In [198]:
np.isnan(d1)

array([False,  True, False])

In [200]:
array21=np.array([[1,np.nan,3],[np.nan,4,5]])

In [201]:
array21

array([[ 1., nan,  3.],
       [nan,  4.,  5.]])

In [202]:
np.isnan(array21)

array([[False,  True, False],
       [ True, False, False]])

In [203]:
arr=np.array([0,1,2,3,4,5])

In [204]:
arr

array([0, 1, 2, 3, 4, 5])

In [206]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])